#!/bin/bash

set -e

usage() {

cat <<USAGE

This command sets the GSLB ratio for each dRouter for a given project/namespace.

Note that it is mandatory to specify ratios for all dRouters defined in gslbState.desired.yaml.

Usage:

project-ratios <project> '{"dRouter1": "ratio1", "dRouter2": "ratio2", ... }'

USAGE

}

#########################################################################################

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

#########################################################################################

ansible-playbook -e "{ projectName: $1, ratios: $2 }" project-ratios.yaml

