#!/bin/bash

set -e

usage() {

cat <<USAGE

This command sets the GSLB ratio for each l7router for a given project/namespace.

Note that it is mandatory to specify ratios for all l7routers defined in gslbState.uncommited.yaml.

Usage:

project-ratios <project> '{"l7router1": "ratio1", "l7router2": "ratio2", ... }'

USAGE

}

#########################################################################################

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

#########################################################################################

ansible-playbook -e "{ projectName: $1, ratios: $2 }" project-ratios.yaml

