#!/bin/sh

set -e

usage() {

cat <<USAGE

This command the evacuates (removes) from GSLB all the routes being hosted in the given project/namespace and dRouter.

Usage:

project-evacuate.sh <project> <dRouter>

USAGE

}

#########################################################################################

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

#########################################################################################

ansible-playbook -e "projectName=$1 dRouter=$2" project-evacuate.yaml



