#!/bin/bash

set -e

usage() {

cat <<USAGE

This command sets the TTL for each l7router for a given project/namespace.

Usage:

project-ttl <project> <ttl>

USAGE

}

#########################################################################################

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

#########################################################################################

ansible-playbook -e "{ projectName: $1, ttl: $2 }" project-ttl.yaml

# TODO: this should be more granular and only remove project's cached files
echo "Invalidate the cache"
rm -rf files.out/*

