#!/bin/sh

set -e

usage() {

cat <<USAGE

This command populates (copies) in the gslbState.desired.yaml file the previously retrieved routes of a given project/dRouter (src dRouter) into another dRouter (dest dRouter).

Before populating, all the routes of the given project are deleted from dest dRouter.

Usage:

project-populate.sh <project> <source dRouter> <dest dRouter>

USAGE

}

#########################################################################################

if [ $# -ne 3 ]; then
  usage
  exit 1
fi

#########################################################################################

ansible-playbook -e "projectName=$1 srcOcpAlias=$2 dstOcpAlias=$3" project-populate.yaml





